name: courier_help
description: An app to help the courier check of items from list of items to be delivered for the day

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:
  firebase_ml_vision: ^0.9.10
  camera: ^0.6.0
  shared_preferences: ^0.5.12
  firebase_core: 0.5.3
  firebase_storage: 5.0.0
  firebase_database: 4.4.0
  cloud_firestore: 0.14.4
  path_provider: ^1.6.24
  excel: ^1.1.5
  lottie: ^0.6.0
  audioplayers: ^0.13.2
  vibration: ^1.7.3


#  firebase_ml_vision: 0.9.10
#  camera: ^0.6.0
#  shared_preferences: ^0.5.12
#  firebase_core: 0.5.3
#  firebase_storage: 5.0.0
#  firebase_database: 4.4.0
#  cloud_firestore: 0.14.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/scan.mp3
  uses-material-design: true
